[project]
name = 'secunda_tt'

[tool.mypy]
disallow_any_generics = false
check_untyped_defs = true
warn_return_any = false
ignore_missing_imports = false
disable_error_code = ['empty-body', 'method-assign']
exclude = ['alembic/']
